/**
 * Drug reference database.
 *
 * Required fields:
 *   - name      (string)  display name incl. brand
 *   - generic   (string)  generic name
 *   - category  (string)  'HD' | 'CV' | 'DM' | 'Other'
 *
 * Dose-seed fields (AI-generated, awaiting physician verification):
 *   - dosage    (string)  short reference dose, renal-adjusted where relevant
 *   - source    (string)  'AI-seed' | citation after human review
 *   - verified  (boolean) false = AI-seeded, true = physician-reviewed
 *   - riskClass (string)  'narrow-ti' for narrow therapeutic index drugs
 *
 * SAFETY: entries with verified=false are AI-seeded dose hints only.
 * A physician must review and flip verified→true per drug before clinical use.
 */
export const MEDICATIONS = [
  // === HD หลัก ===
  { name: 'EPO (Recormon)', generic: 'Epoetin beta', category: 'HD',
    dosage: '2000-4000 U SC/IV 3x/wk; adjust to Hb 10-11.5', source: 'AI-seed', verified: false },
  { name: 'EPO (Eprex)', generic: 'Epoetin alfa', category: 'HD',
    dosage: '2000-4000 U SC/IV 3x/wk; adjust to Hb 10-11.5', source: 'AI-seed', verified: false },
  { name: 'Aranesp', generic: 'Darbepoetin alfa', category: 'HD',
    dosage: '0.45 mcg/kg SC/IV q1-2wk; adjust to Hb 10-11.5', source: 'AI-seed', verified: false },
  { name: 'CERA (Mircera)', generic: 'Methoxy PEG-epoetin beta', category: 'HD',
    dosage: '0.6 mcg/kg IV/SC q2wk init → q4wk maint', source: 'AI-seed', verified: false },
  { name: 'Venofer', generic: 'Iron sucrose', category: 'HD',
    dosage: '100 mg IV per HD session; total course 1000 mg', source: 'AI-seed', verified: false },
  { name: 'Ferinject', generic: 'Ferric carboxymaltose (FCM)', category: 'HD',
    dosage: '500-1000 mg IV; max 20 mg/kg/dose', source: 'AI-seed', verified: false },
  { name: 'Iron dextran', generic: 'Iron dextran', category: 'HD',
    dosage: '25 mg test dose → 100 mg IV/session; total per formula', source: 'AI-seed', verified: false },
  { name: 'Calcium carbonate (CaCO3)', generic: 'Calcium carbonate', category: 'HD',
    dosage: '500-1500 mg elemental Ca TID with meals as PO4 binder', source: 'AI-seed', verified: false },
  { name: 'Sevelamer', generic: 'Sevelamer', category: 'HD',
    dosage: '800 mg TID with meals; titrate to PO4 target', source: 'AI-seed', verified: false },
  { name: 'Lanthanum carbonate', generic: 'Lanthanum', category: 'HD',
    dosage: '250-500 mg TID with meals; chew before swallow', source: 'AI-seed', verified: false },
  { name: 'Aluminium hydroxide', generic: 'Aluminium hydroxide', category: 'HD',
    dosage: '300-600 mg TID with meals; short-term only (≤4 wk)', source: 'AI-seed', verified: false },
  { name: 'Alfacalcidol', generic: 'Alfacalcidol', category: 'HD',
    dosage: '0.25-0.5 mcg/day PO; titrate per Ca/PTH', source: 'AI-seed', verified: false },
  { name: 'Calcitriol', generic: 'Calcitriol', category: 'HD',
    dosage: '0.25-0.5 mcg/day PO or 1-2 mcg IV 3x/wk post-HD', source: 'AI-seed', verified: false },
  { name: 'Ergocalciferol', generic: 'Ergocalciferol (Vitamin D2)', category: 'HD',
    dosage: '50,000 U/wk × 8-12 wk if 25-OH VitD <30', source: 'AI-seed', verified: false },
  { name: 'Cholecalciferol', generic: 'Cholecalciferol (Vitamin D3)', category: 'HD',
    dosage: '1,000-5,000 U/day maintenance', source: 'AI-seed', verified: false },
  { name: 'Cinacalcet', generic: 'Cinacalcet', category: 'HD',
    dosage: '25-30 mg OD; titrate q2-4wk to max 180 mg/day', source: 'AI-seed', verified: false },
  { name: 'Etelcalcetide', generic: 'Etelcalcetide', category: 'HD',
    dosage: '5 mg IV 3x/wk post-HD; titrate per PTH', source: 'AI-seed', verified: false },
  { name: 'Heparin', generic: 'Heparin', category: 'HD',
    dosage: 'HD: 1000-2000 U bolus + 500-1000 U/hr; adjust per ACT', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Enoxaparin (Clexane)', generic: 'Enoxaparin', category: 'HD',
    dosage: '1 mg/kg q12h; CrCl<30: 1 mg/kg OD; HD anticoag: 0.5-1 mg/kg', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Sodium bicarbonate', generic: 'Sodium bicarbonate', category: 'HD',
    dosage: '650-1300 mg PO TID; target serum HCO3 ≥22', source: 'AI-seed', verified: false },

  // === Cardiovascular ===
  { name: 'Enalapril', generic: 'Enalapril', category: 'CV',
    dosage: '2.5-20 mg BD; CKD: start 2.5 mg, titrate', source: 'AI-seed', verified: false },
  { name: 'Ramipril', generic: 'Ramipril', category: 'CV',
    dosage: '1.25-10 mg OD; CKD: start 1.25 mg', source: 'AI-seed', verified: false },
  { name: 'Lisinopril', generic: 'Lisinopril', category: 'CV',
    dosage: '5-40 mg OD; CrCl<30: start 2.5 mg', source: 'AI-seed', verified: false },
  { name: 'Perindopril', generic: 'Perindopril', category: 'CV',
    dosage: '2-8 mg OD; CrCl<30: 2 mg OD', source: 'AI-seed', verified: false },
  { name: 'Losartan', generic: 'Losartan', category: 'CV',
    dosage: '25-100 mg OD; no renal adj needed', source: 'AI-seed', verified: false },
  { name: 'Valsartan', generic: 'Valsartan', category: 'CV',
    dosage: '40-320 mg OD; no renal adj needed', source: 'AI-seed', verified: false },
  { name: 'Irbesartan', generic: 'Irbesartan', category: 'CV',
    dosage: '150-300 mg OD; no renal adj needed', source: 'AI-seed', verified: false },
  { name: 'Telmisartan', generic: 'Telmisartan', category: 'CV',
    dosage: '20-80 mg OD; no renal adj needed', source: 'AI-seed', verified: false },
  { name: 'Olmesartan', generic: 'Olmesartan', category: 'CV',
    dosage: '10-40 mg OD; no renal adj needed', source: 'AI-seed', verified: false },
  { name: 'Candesartan', generic: 'Candesartan', category: 'CV',
    dosage: '4-32 mg OD; no renal adj needed', source: 'AI-seed', verified: false },
  { name: 'Amlodipine', generic: 'Amlodipine', category: 'CV',
    dosage: '2.5-10 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Nifedipine', generic: 'Nifedipine', category: 'CV',
    dosage: '30-60 mg SR OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Diltiazem', generic: 'Diltiazem', category: 'CV',
    dosage: '120-360 mg SR OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Verapamil', generic: 'Verapamil', category: 'CV',
    dosage: '120-480 mg/day div BD-TID; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Manidipine (Madiplot)', generic: 'Manidipine', category: 'CV',
    dosage: '10-20 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Atenolol', generic: 'Atenolol', category: 'CV',
    dosage: '25-100 mg OD; CrCl<35: 25-50 mg OD; HD: post-HD', source: 'AI-seed', verified: false },
  { name: 'Metoprolol', generic: 'Metoprolol', category: 'CV',
    dosage: '25-200 mg BD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Bisoprolol', generic: 'Bisoprolol', category: 'CV',
    dosage: '1.25-10 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Carvedilol', generic: 'Carvedilol', category: 'CV',
    dosage: '3.125-25 mg BD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Propranolol', generic: 'Propranolol', category: 'CV',
    dosage: '10-40 mg BD-TID; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Furosemide', generic: 'Furosemide', category: 'CV',
    dosage: '20-80 mg OD-BD PO; HD pts: higher doses may be needed', source: 'AI-seed', verified: false },
  { name: 'HCTZ', generic: 'Hydrochlorothiazide', category: 'CV',
    dosage: '12.5-25 mg OD; ineffective if CrCl<30', source: 'AI-seed', verified: false },
  { name: 'Spironolactone', generic: 'Spironolactone', category: 'CV',
    dosage: '12.5-50 mg OD; avoid if K>5.0 or CrCl<30', source: 'AI-seed', verified: false },
  { name: 'Finerenone', generic: 'Finerenone', category: 'CV',
    dosage: 'eGFR≥60: 20 mg OD; eGFR 25-59: 10 mg OD; K must be <5.0', source: 'AI-seed', verified: false },
  { name: 'Hydralazine', generic: 'Hydralazine', category: 'CV',
    dosage: '25-100 mg TID-QID; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Minoxidil', generic: 'Minoxidil', category: 'CV',
    dosage: '2.5-10 mg OD-BD; max 40 mg/day', source: 'AI-seed', verified: false },
  { name: 'Prazosin', generic: 'Prazosin', category: 'CV',
    dosage: '1-5 mg BD-TID; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Doxazosin', generic: 'Doxazosin', category: 'CV',
    dosage: '1-8 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Aspirin (ASA)', generic: 'Aspirin', category: 'CV',
    dosage: '81-325 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Clopidogrel', generic: 'Clopidogrel', category: 'CV',
    dosage: '75 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Ticagrelor', generic: 'Ticagrelor', category: 'CV',
    dosage: '90 mg BD; no renal adj; avoid in HD', source: 'AI-seed', verified: false },
  { name: 'Prasugrel', generic: 'Prasugrel', category: 'CV',
    dosage: '10 mg OD (5 mg if <60 kg); no renal adj', source: 'AI-seed', verified: false },
  { name: 'Warfarin', generic: 'Warfarin', category: 'CV',
    dosage: '2-5 mg OD; target INR 2-3; CKD: lower doses, frequent INR', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Rivaroxaban', generic: 'Rivaroxaban', category: 'CV',
    dosage: 'AF: 20 mg OD; CrCl 15-49: 15 mg OD; avoid CrCl<15', source: 'AI-seed', verified: false },
  { name: 'Apixaban', generic: 'Apixaban', category: 'CV',
    dosage: 'AF: 5 mg BD; reduce to 2.5 mg BD if ≥2 of: age≥80/wt≤60kg/Cr≥1.5', source: 'AI-seed', verified: false },
  { name: 'Dabigatran', generic: 'Dabigatran', category: 'CV',
    dosage: 'AF: 150 mg BD; CrCl 30-50: 110 mg BD; avoid CrCl<30', source: 'AI-seed', verified: false },
  { name: 'Atorvastatin', generic: 'Atorvastatin', category: 'CV',
    dosage: '10-80 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Rosuvastatin', generic: 'Rosuvastatin', category: 'CV',
    dosage: '5-20 mg OD; CrCl<30: start 5 mg, max 10 mg', source: 'AI-seed', verified: false },
  { name: 'Simvastatin', generic: 'Simvastatin', category: 'CV',
    dosage: '10-40 mg OD hs; CKD: start 10 mg', source: 'AI-seed', verified: false },
  { name: 'Pravastatin', generic: 'Pravastatin', category: 'CV',
    dosage: '10-40 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Ezetimibe', generic: 'Ezetimibe', category: 'CV',
    dosage: '10 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Fenofibrate', generic: 'Fenofibrate', category: 'CV',
    dosage: '160 mg OD; CrCl 30-59: 54 mg OD; avoid CrCl<30', source: 'AI-seed', verified: false },
  { name: 'Gemfibrozil', generic: 'Gemfibrozil', category: 'CV',
    dosage: '600 mg BD; CrCl<30: consider dose reduction', source: 'AI-seed', verified: false },
  { name: 'ISDN', generic: 'Isosorbide dinitrate', category: 'CV',
    dosage: '10-40 mg TID; no renal adj', source: 'AI-seed', verified: false },
  { name: 'ISMN', generic: 'Isosorbide mononitrate', category: 'CV',
    dosage: '30-60 mg SR OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Digoxin', generic: 'Digoxin', category: 'CV',
    dosage: '0.0625-0.125 mg OD in CKD/HD; target level 0.5-0.9 ng/mL', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Amiodarone', generic: 'Amiodarone', category: 'CV',
    dosage: 'Load 200 mg TID × 1wk → 200 mg OD; no renal adj; monitor thyroid/liver', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },

  // === DM ===
  { name: 'Insulin RI', generic: 'Regular Insulin', category: 'DM',
    dosage: 'Individualized; CKD/HD: reduce dose 25-50%, monitor closely', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Insulin NPH', generic: 'NPH Insulin', category: 'DM',
    dosage: 'Individualized; CKD/HD: reduce dose 25-50%, monitor closely', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Insulin Glargine', generic: 'Insulin glargine', category: 'DM',
    dosage: 'Start 10 U OD; CKD/HD: reduce dose 25-50%', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Insulin Detemir', generic: 'Insulin detemir', category: 'DM',
    dosage: 'Start 10 U OD-BD; CKD/HD: reduce dose 25-50%', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Insulin Degludec', generic: 'Insulin degludec', category: 'DM',
    dosage: 'Start 10 U OD; CKD/HD: reduce dose 25-50%', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Insulin Aspart', generic: 'Insulin aspart', category: 'DM',
    dosage: 'Individualized pre-meal; CKD/HD: reduce dose 25-50%', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Insulin Lispro', generic: 'Insulin lispro', category: 'DM',
    dosage: 'Individualized pre-meal; CKD/HD: reduce dose 25-50%', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Metformin', generic: 'Metformin', category: 'DM',
    dosage: '500-1000 mg BD; eGFR 30-44: max 1000 mg/d; eGFR<30: avoid', source: 'AI-seed', verified: false },
  { name: 'Dapagliflozin (Forxiga)', generic: 'Dapagliflozin', category: 'DM',
    dosage: '10 mg OD; do not initiate if eGFR<20; can continue if started', source: 'AI-seed', verified: false },
  { name: 'Empagliflozin (Jardiance)', generic: 'Empagliflozin', category: 'DM',
    dosage: '10-25 mg OD; do not initiate if eGFR<20; can continue if started', source: 'AI-seed', verified: false },
  { name: 'Canagliflozin (Invokana)', generic: 'Canagliflozin', category: 'DM',
    dosage: '100-300 mg OD; eGFR 30-59: max 100 mg; eGFR<30: avoid', source: 'AI-seed', verified: false },
  { name: 'Semaglutide (Ozempic)', generic: 'Semaglutide', category: 'DM',
    dosage: '0.25 mg SC/wk → 0.5 → 1 mg; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Liraglutide (Victoza)', generic: 'Liraglutide', category: 'DM',
    dosage: '0.6 mg SC/day → 1.2 → 1.8 mg; no renal adj; caution eGFR<15', source: 'AI-seed', verified: false },
  { name: 'Dulaglutide (Trulicity)', generic: 'Dulaglutide', category: 'DM',
    dosage: '0.75 mg SC/wk → 1.5 mg; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Linagliptin (Trajenta)', generic: 'Linagliptin', category: 'DM',
    dosage: '5 mg OD; no renal adj (non-renal elimination)', source: 'AI-seed', verified: false },
  { name: 'Sitagliptin (Januvia)', generic: 'Sitagliptin', category: 'DM',
    dosage: '100 mg OD; eGFR 30-44: 50 mg; eGFR<30: 25 mg', source: 'AI-seed', verified: false },
  { name: 'Vildagliptin (Galvus)', generic: 'Vildagliptin', category: 'DM',
    dosage: '50 mg BD; eGFR<50: 50 mg OD', source: 'AI-seed', verified: false },
  { name: 'Glipizide (Minidiab)', generic: 'Glipizide', category: 'DM',
    dosage: '2.5-10 mg OD-BD; preferred SU in CKD (hepatic metab)', source: 'AI-seed', verified: false },
  { name: 'Gliclazide (Diamicron)', generic: 'Gliclazide', category: 'DM',
    dosage: '30-120 mg MR OD; CKD: start low, monitor hypo', source: 'AI-seed', verified: false },
  { name: 'Glimepiride (Amaryl)', generic: 'Glimepiride', category: 'DM',
    dosage: '1-4 mg OD; CKD: start 1 mg, caution hypo', source: 'AI-seed', verified: false },
  { name: 'Acarbose (Glucobay)', generic: 'Acarbose', category: 'DM',
    dosage: '25-100 mg TID with meals; avoid if eGFR<25', source: 'AI-seed', verified: false },
  { name: 'Pioglitazone (Actos)', generic: 'Pioglitazone', category: 'DM',
    dosage: '15-30 mg OD; no renal adj; avoid if fluid overload/HF', source: 'AI-seed', verified: false },
  { name: 'Lixisenatide', generic: 'Lixisenatide', category: 'DM',
    dosage: '10 mcg SC/day × 2wk → 20 mcg; caution eGFR<30', source: 'AI-seed', verified: false },
  { name: 'Exenatide', generic: 'Exenatide', category: 'DM',
    dosage: '5 mcg SC BD → 10 mcg; avoid eGFR<30', source: 'AI-seed', verified: false },

  // === อื่น ๆ ===
  { name: 'Omeprazole', generic: 'Omeprazole', category: 'Other',
    dosage: '20-40 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Esomeprazole', generic: 'Esomeprazole', category: 'Other',
    dosage: '20-40 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Pantoprazole', generic: 'Pantoprazole', category: 'Other',
    dosage: '20-40 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Ranitidine', generic: 'Ranitidine', category: 'Other',
    dosage: '150 mg BD; CrCl<50: 150 mg OD', source: 'AI-seed', verified: false },
  { name: 'Famotidine', generic: 'Famotidine', category: 'Other',
    dosage: '20-40 mg OD; CrCl<50: 20 mg OD or q48h', source: 'AI-seed', verified: false },
  { name: 'Allopurinol', generic: 'Allopurinol', category: 'Other',
    dosage: '100 mg OD; CrCl<30: start 50 mg OD; titrate slowly', source: 'AI-seed', verified: false },
  { name: 'Febuxostat', generic: 'Febuxostat', category: 'Other',
    dosage: '40-80 mg OD; mild-mod CKD: no adj; severe: limited data', source: 'AI-seed', verified: false },
  { name: 'Colchicine', generic: 'Colchicine', category: 'Other',
    dosage: '0.6 mg OD-BD; CrCl<30: 0.3 mg OD; avoid in HD', source: 'AI-seed', verified: false },
  { name: 'Gabapentin', generic: 'Gabapentin', category: 'Other',
    dosage: '300 mg OD → titrate; CrCl 15-29: 100-300 mg OD; HD: 100-300 mg post-HD', source: 'AI-seed', verified: false },
  { name: 'Pregabalin', generic: 'Pregabalin', category: 'Other',
    dosage: '75 mg OD-BD; CrCl<30: 25-75 mg OD; HD: supplement post-HD', source: 'AI-seed', verified: false },
  { name: 'Sertraline', generic: 'Sertraline', category: 'Other',
    dosage: '25-200 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Fluoxetine', generic: 'Fluoxetine', category: 'Other',
    dosage: '20-40 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Escitalopram', generic: 'Escitalopram', category: 'Other',
    dosage: '5-20 mg OD; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Paracetamol', generic: 'Paracetamol', category: 'Other',
    dosage: '500-1000 mg q6-8h; max 3 g/day in CKD', source: 'AI-seed', verified: false },
  { name: 'Amoxicillin', generic: 'Amoxicillin', category: 'Other',
    dosage: '250-500 mg TID; CrCl<30: 250-500 mg q12h', source: 'AI-seed', verified: false },
  { name: 'Augmentin', generic: 'Amoxicillin-clavulanate', category: 'Other',
    dosage: '625 mg TID; CrCl<30: 625 mg q12h', source: 'AI-seed', verified: false },
  { name: 'Cephalexin', generic: 'Cephalexin', category: 'Other',
    dosage: '250-500 mg QID; CrCl 10-30: q8-12h; HD: supplement post-HD', source: 'AI-seed', verified: false },
  { name: 'Ceftriaxone', generic: 'Ceftriaxone', category: 'Other',
    dosage: '1-2 g IV OD; no renal adj (biliary excretion)', source: 'AI-seed', verified: false },
  { name: 'Tazocin', generic: 'Piperacillin-tazobactam', category: 'Other',
    dosage: '4.5 g IV q6-8h; CrCl<20: 4.5 g q8h; HD: 4.5 g q8h + post-HD dose', source: 'AI-seed', verified: false },
  { name: 'Meropenem', generic: 'Meropenem', category: 'Other',
    dosage: '0.5-1 g IV q8h; CrCl 10-25: q12h; CrCl<10: q24h; HD: post-HD dose', source: 'AI-seed', verified: false },
  { name: 'Vancomycin', generic: 'Vancomycin', category: 'Other',
    dosage: 'HD: 15-20 mg/kg post-HD; target trough 15-20 mcg/mL; redose per level', source: 'AI-seed', verified: false, riskClass: 'narrow-ti' },
  { name: 'Ciprofloxacin', generic: 'Ciprofloxacin', category: 'Other',
    dosage: '250-500 mg BD PO; CrCl<30: 250-500 mg q24h', source: 'AI-seed', verified: false },
  { name: 'Levofloxacin', generic: 'Levofloxacin', category: 'Other',
    dosage: '500-750 mg OD; CrCl 20-49: 250-500 mg q24h; CrCl<20: 250-500 mg q48h', source: 'AI-seed', verified: false },
  { name: 'Fluconazole', generic: 'Fluconazole', category: 'Other',
    dosage: '100-400 mg OD; CrCl<50: 50% dose; HD: full dose post-HD', source: 'AI-seed', verified: false },

  // === Pain / NSAIDs ===
  { name: 'Ibuprofen', generic: 'Ibuprofen', category: 'Pain',
    dosage: '200-400 mg TID; avoid in CKD 4-5/HD (nephrotoxic)', source: 'AI-seed', verified: false },
  { name: 'Naproxen', generic: 'Naproxen', category: 'Pain',
    dosage: '250-500 mg BD; avoid in CKD 4-5/HD', source: 'AI-seed', verified: false },
  { name: 'Diclofenac', generic: 'Diclofenac', category: 'Pain',
    dosage: '25-50 mg BD-TID; avoid in CKD 4-5/HD', source: 'AI-seed', verified: false },
  { name: 'Mefenamic acid', generic: 'Mefenamic acid', category: 'Pain',
    dosage: '250-500 mg TID; avoid in CKD (nephrotoxic + GI risk)', source: 'AI-seed', verified: false },
  { name: 'Celecoxib', generic: 'Celecoxib', category: 'Pain',
    dosage: '100-200 mg OD-BD; avoid in severe CKD/HD', source: 'AI-seed', verified: false },
  { name: 'Etoricoxib', generic: 'Etoricoxib', category: 'Pain',
    dosage: '60-120 mg OD; avoid in CrCl<30', source: 'AI-seed', verified: false },
  { name: 'Piroxicam', generic: 'Piroxicam', category: 'Pain',
    dosage: '10-20 mg OD; avoid in CKD 4-5/HD', source: 'AI-seed', verified: false },
  { name: 'Indomethacin', generic: 'Indomethacin', category: 'Pain',
    dosage: '25-50 mg BD-TID; avoid in CKD 4-5/HD', source: 'AI-seed', verified: false },
  { name: 'Tramadol', generic: 'Tramadol', category: 'Pain',
    dosage: '50-100 mg q4-6h; CrCl<30: 50-100 mg q12h; max 200 mg/d', source: 'AI-seed', verified: false },
  { name: 'Codeine', generic: 'Codeine', category: 'Pain',
    dosage: '15-60 mg q4-6h; CKD: reduce dose; avoid in HD', source: 'AI-seed', verified: false },
  { name: 'Tolperisone', generic: 'Tolperisone', category: 'Pain',
    dosage: '50-150 mg TID; no renal adj', source: 'AI-seed', verified: false },
  { name: 'Baclofen', generic: 'Baclofen', category: 'Pain',
    dosage: '5 mg TID → titrate; CrCl<30: 5 mg OD; avoid in HD (CNS toxicity)', source: 'AI-seed', verified: false },
]

export function searchMedications(query) {
  if (!query || query.trim().length < 1) return []
  const q = query.toLowerCase()
  return MEDICATIONS.filter(
    (m) => m.name.toLowerCase().includes(q) || m.generic.toLowerCase().includes(q)
  ).slice(0, 8)
}

/** Look up dose-seed info for a drug by display name. */
export function getDrugInfo(name) {
  if (!name) return null
  const n = name.toLowerCase()
  return MEDICATIONS.find((m) => m.name.toLowerCase() === n) || null
}

export const TIMING_OPTIONS = [
  'ac (ก่อนอาหาร)',
  'pc (หลังอาหาร)',
  'hs (ก่อนนอน)',
  'หลัง HD',
  'พร้อมอาหาร',
  'เช้า-เย็น',
  'เช้า-กลางวัน-เย็น',
  'เมื่อจำเป็น (prn)',
  'อื่น ๆ',
]

export const FREQUENCY_OPTIONS = [
  'OD',
  'BD',
  'TID',
  'QID',
  '3x/wk (หลัง HD)',
  '2x/wk',
  '1x/wk',
  'q 2 weeks',
  'q 4 weeks',
  'prn',
  'อื่น ๆ',
]
